#!/bin/bash
set -e
IMG="/home/tfox/systemcore-rpi5-guide/systemcore-pi5b-beta9.img"
losetup -D 2>/dev/null

echo "=== BOOT PARTITION ==="
MNT=$(mktemp -d)
mount -o loop,offset=512,ro "$IMG" "$MNT"
echo "Kernel:"
file "$MNT/Image"
echo "Config kernel line:"
grep "^kernel=" "$MNT/config.txt"
echo "Initrd files:"
ls -la "$MNT"/init* "$MNT"/*.cpio* 2>/dev/null || echo "  (none)"
echo "All .img files:"
ls "$MNT"/*.img 2>/dev/null || echo "  (none)"
umount "$MNT"
rmdir "$MNT"

echo ""
echo "=== ROOTFS A ==="
MNT=$(mktemp -d)
mount -o loop,offset=$((131073*512)),ro "$IMG" "$MNT"
echo "/lib type:"
ls -lad "$MNT/lib"
echo "/usr/lib type:"
ls -lad "$MNT/usr/lib"
echo "Dynamic linker:"
ls -la "$MNT"/lib/ld* "$MNT"/usr/lib/ld* 2>/dev/null || echo "  (none found)"
echo "/lib contents:"
ls "$MNT/lib/"
echo "/sbin/init:"
ls -la "$MNT/sbin/init"
echo "/bin/sh:"
ls -la "$MNT/bin/sh"
echo "/bin/bash:"
file "$MNT/bin/bash" 2>/dev/null || echo "  (not found)"
echo "readelf /bin/bash:"
readelf -l "$MNT/bin/bash" 2>/dev/null | grep -A1 LOAD || echo "  (readelf failed)"
echo "ldd-style check:"
readelf -d "$MNT/bin/bash" 2>/dev/null | grep NEEDED || echo "  (static)"
echo "interp:"
readelf -l "$MNT/bin/bash" 2>/dev/null | grep "interpreter" || echo "  (no interp)"
umount "$MNT"
rmdir "$MNT"
echo ""
echo "=== DONE ==="
